Parcel copy
relaycorp/awala-ping-android pull request #269
Opened 2023-01-16 20:44 UTC by Filmaluco

![Screenshot 2023-01-16 at 19 29 16](https://user-images.githubusercontent.com/20781703/212762393-1afef840-447d-48fa-97cf-467aa84ddc50.png)

2023-01-17 11:37 UTC, gnarea requested changes
Based on the screenshot you shared, this PR seems to introduce changes to the horizontal lines that separate fields. Some lines are dark grey, other light grey, and some fields are not separated by any lines.

This is what I see on my phone right now:

![Screenshot_20230117-113350](https://user-images.githubusercontent.com/369863/212888866-c369b8c6-9bf9-402c-aad4-47925936c4da.png)

I think the original design should be preserved.

2023-01-17 11:37 UTC, gnarea commented on app/src/main/res/values/strings.xml
> +    <string name="parcel_id">Id (parcel)</string>
With this new field, the UI looks quite odd. I think we should rename:

- "Id" -> "Ping id".
- "Id (parcel)" -> "Parcel id".

2023-01-17 11:39 UTC, gnarea commented
BTW, I believe you want to use `master` as the target branch. I didn't want to change it myself because the current target isn't in sync with `master` (same code, different commits).

2023-01-17 18:27 UTC, Filmaluco commented
> Based on the screenshot you shared, this PR seems to introduce changes to the horizontal lines that separate fields. Some lines are dark grey, other light grey, and some fields are not separated by any lines.
> 
> This is what I see on my phone right now:
> 
> ![Screenshot_20230117-113350](https://user-images.githubusercontent.com/369863/212888866-c369b8c6-9bf9-402c-aad4-47925936c4da.png)
> 
> I think the original design should be preserved.

no changes, the reason it seems like that its because its a XML preview :) 
I did against the 33 branch because we never merged it... we can now merge it, and it should be merge first.
Then this one will automatically go to master

2023-01-18 13:46 UTC, gnarea commented
@Filmaluco, makes sense. #267 is now merged. I thought we were waiting for you to fix something in the instrumentation tests because they were failing last time I looked.

2023-01-19 10:25 UTC, gnarea commented
BTW @Filmaluco, did you test this? Asking because of the Android Studio screenshot, so not clear if you tested it on an actual device with the gateway.

2023-01-20 15:11 UTC, Filmaluco commented
@gnarea I tested with an actual device, did not do the test with gateway, since I was waiting on the feedback about GCP issue. will make a test on Monday at the office, at home, I only have 1 android to test.

2023-01-20 15:14 UTC, gnarea commented
> I tested with an actual device, did not do the test with gateway  since I was waiting on the feedback about GCP issue.

Keep in mind that the GCP issue only affects the the Courier app, not any other app or library.

> will make a test on Monday at the office, at home, I only have 1 android to test.

👍🏾

2023-01-20 16:06 UTC, Filmaluco commented
> > I tested with an actual device, did not do the test with gateway  since I was waiting on the feedback about GCP issue.
> 
> Keep in mind that the GCP issue only affects the the Courier app, not any other app or library.
> 
> > will make a test on Monday at the office, at home, I only have 1 android to test.
> 
> 👍🏾

in that case, its tested :) you can merge.

2023-01-31 17:50 UTC, Filmaluco commented
@gnarea just finished testing this version of ping against gateway from https://github.com/relaycorp/relaynet-gateway-android/pull/675.

![image](https://user-images.githubusercontent.com/20781703/215842157-2f796917-5a3b-454a-aa1e-bcb455940e6e.png)

2023-01-31 22:45 UTC, gnarea approved these changes
Amazing, thanks!

2023-01-31 22:46 UTC, merged