fix: Ping state
relaycorp/awala-ping-android pull request #33
Opened 2021-04-05 20:03 UTC by sdsantos

Closes #27

2021-04-05 21:08 UTC, gnarea approved these changes

2021-04-05 21:20 UTC, gnarea requested changes
This is mostly the first solution I described in #27, but it's displaying the status text instead of an icon, which I believe is going to make more likely the issue of this text running into the public address if it's too long.

I think it'd be best to either replace the text with the icon or move the text to a new row.  I have a slight preference for the former as it'd be consistent with the home screen.

2021-04-08 15:59 UTC, sdsantos commented
> This is mostly the first solution I described in #27, but it's displaying the status text instead of an icon, which I believe is going to make more likely the issue of this text running into the public address if it's too long.
> 
> I think it'd be best to either replace the text with the icon or move the text to a new row. I have a slight preference for the former as it'd be consistent with the home screen.

Icon it is.

2021-04-08 17:06 UTC, gnarea approved these changes

2021-04-08 17:19 UTC, merged